// Mocks generated by Mockito 5.3.0 from annotations
// in one_health_hospital_app/test/fetch_profile_data_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:one_health_hospital_app/repositories/user_get_profile/user_get_profile_services.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [GetUserProfileServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserProfileServices extends _i1.Mock
    implements _i3.GetUserProfileServices {
  MockGetUserProfileServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> getUserProfileDetails(
          {String? token, String? id}) =>
      (super.noSuchMethod(Invocation.method(#getUserProfileDetails, [], {#token: token, #id: id}),
          returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                  this,
                  Invocation.method(#getUserProfileDetails, [], {
                    #token: token,
                    #id: id
                  })))) as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> changeUserPassword(
          {String? token,
          String? id,
          String? oldPassword,
          String? newPassword}) =>
      (super.noSuchMethod(Invocation.method(#changeUserPassword, [], {#token: token, #id: id, #oldPassword: oldPassword, #newPassword: newPassword}),
          returnValue: _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
              this,
              Invocation.method(#changeUserPassword, [], {
                #token: token,
                #id: id,
                #oldPassword: oldPassword,
                #newPassword: newPassword
              })))) as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> editProfile(
          {_i3.EditProfileModel? editProfileModel,
          bool? isImageChaned,
          String? id,
          String? token}) =>
      (super.noSuchMethod(
          Invocation.method(#editProfile, [], {
            #editProfileModel: editProfileModel,
            #isImageChaned: isImageChaned,
            #id: id,
            #token: token
          }),
          returnValue:
              _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
                  this,
                  Invocation.method(#editProfile, [], {
                    #editProfileModel: editProfileModel,
                    #isImageChaned: isImageChaned,
                    #id: id,
                    #token: token
                  })))) as _i4.Future<_i2.Response<dynamic>>);
}
